name: CI

on:
  push:
    branches: [ master, main, feature/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: xmlsvc
          POSTGRES_PASSWORD: xmlsvc
          POSTGRES_DB: xmlsvc
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U xmlsvc"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      minio:
        image: bitnami/minio:latest
        ports: ["9000:9000"]
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
          MINIO_DEFAULT_BUCKETS: xmlsvc
        options: >-
          --health-cmd="curl -fsS http://localhost:9000/minio/health/ready || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    env:
      PYTHONPATH: ${{ github.workspace }}   # <— ключевой фикс
      DATABASE_URL: postgresql+psycopg://xmlsvc:xmlsvc@localhost:5432/xmlsvc
      S3_ENDPOINT: http://localhost:9000
      S3_BUCKET: xmlsvc
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Alembic upgrade
        run: python -m alembic upgrade head

      - name: Run tests
        run: pytest -q
